# This file may be used to create a conda environment using:
# $ conda create --name gprMax --file <this file>

name: gprMax
dependencies:
- python>3.6
- colorama
- cython
- h5py
- jupyter
- matplotlib
# - numpy
- psutil
- scipy

- pip:
 # - mpi4py
  - numpy>1.15.4
 # - pycuda
  - terminaltables
  - tqdm
